name: test1

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - id: step1
      name: 输出hello
      env:
        asgc: '傲世孤尘'
      run: echo 'hello $asgc'

  unit-test:
    needs: [build]
