name: test1

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - id: step1
        name: hello
        run: echo 'hello aoshiguchen...'
  unit-test:
    needs: build
